services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    secrets:
      - secret_group_token
      - secret_admin_token
    environment:
      SECRET_GROUP_TOKEN: /run/secrets/secret_group_token
      SECRET_ADMIN_TOKEN: /run/secrets/secret_admin_token
    ports:
      - "4000:4000"

secrets:
  secret_group_token:
    file: secret_group_token.txt
  secret_admin_token:
    file: secret_admin_token.txt
