services:
  main:
    build: .
    secrets:
      - secret_group_token
      - secret_admin_token
    environment:
      DB: /db/ask.db
      SCHEMA: schema.sql
      LOG_DIR: /log
      SECRET_GROUP_TOKEN: /run/secrets/secret_group_token
      SECRET_ADMIN_TOKEN: /run/secrets/secret_admin_token
    volumes:
      - type: bind
        source: ${DB_LOCAL_PATH}
        target: /db
      - type: bind
        source: ${LOG_LOCAL_PATH}
        target: /log

  web_sqlite:
    build: ./sqlite-web/docker
    environment:
      SQLITE_DATABASE: /db/ask.db
    volumes:
      - type: bind
        source: ${DB_LOCAL_PATH}
        target: /db
    ports:
      - "8080:8080"
    # without flask log
    attach: false

secrets:
  secret_group_token:
    file: secret_group_token.txt
  secret_admin_token:
    file: secret_admin_token.txt
