FROM golang:1.21.3-alpine
WORKDIR /app/
COPY ./src go.mod go.sum schema.sql /app/

RUN mkdir log
RUN CGO_ENABLED=0 go install -ldflags "-s -w -extldflags '-static'" github.com/go-delve/delve/cmd/dlv@latest
RUN CGO_ENABLED=0 go build -gcflags "all=-N -l" -o bot .

EXPOSE 4000:4000

CMD [ "/go/bin/dlv", "--listen=:4000", "--headless=true", "--log=true", "--accept-multiclient", "--api-version=2", "exec", "/app/bot" ]